services:
  db:
    image: postgres:16
    env_file: .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres-data:
